#!name=机场名套餐信息
#!desc=显示机场剩余流量信息以及套餐到期日期
#!system=ios
#!复制本文件所有内容到新建本地模块

#订阅链接encode，encode编码地址：https://www.urlencoder.org 用encode后的链接替换''编码后的订阅连接''
#请替换以下''机场名'' ''编码后的订阅连接'' ''重置日''

[Panel]
Sub_info机场名= script-name=Sub_info机场名,update-interval=888

[Script]
Sub_info机场名= type=generic,timeout=10,script-path=https://raw.githubusercontent.com/Twoandz9/Tool/main/Surge/module/Sub-info.js,script-update-interval=0,argument=url=编码后的订阅连接&title=机场名&reset_day=重置日&icon=sun.min&color=f2d244

# 进阶操作
# 可选参数 &reset_day，后面的数字替换成流量每月重置的日期，如1号就写1，8号就写8。如"&reset_day=8",不加该参数不显示流量重置信息。
# 可选参数 &expire，机场链接不带expire信息的，可以手动传入expire参数，如"&expire=2022-02-01",注意一定要按照yyyy-MM-dd的格式。不希望显示到期信息也可以添加&expire=false取消显示。
# 可选参数"&title=xxx" 可以自定义标题。
# 可选参数"&icon=xxx" 可以自定义图标，内容为任意有效的 SF Symbol Name，如 bolt.horizontal.circle.fill，详细可以下载app https://apps.apple.com/cn/app/symbols-explorer/id1612933742
# 可选参数"color=xxx" 当使用 icon 字段时，可传入 color 字段控制图标颜色，字段内容为颜色的 HEX 编码。如：&color=#007aff
