# 菜鸟去广告
# 过滤菜鸟广告（原菜鸟裹裹）

[Rule]
DOMAIN, amdc.m.taobao.com, REJECT

[URL Rewrite]
# 通用广告请求[包含开屏广告]
^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.(show|mshow)\.cn reject-img

[Script]
# 首页中部的惊喜福利推广
cainiao-remove-ads = type=http-response,pattern=^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.nbpresentation\.protocol\.homepage\.get\.cn,requires-body=1,script-path=https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Resource/Script/Cainiao/Cainiao_remove_ads.js,tag=首页中部的惊喜福利推广
# 搜索框下方今日好物推荐
cainiao-remove-ads = type=http-response,pattern=^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.adkeyword,requires-body=1,script-path=https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Resource/Script/Cainiao/Cainiao_remove_ads.js,tag=搜索框下方今日好物推荐
# 首页底部商品推广
cainiao-remove-ads = type=http-response,pattern=^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.index\.cn,requires-body=1,script-path=https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Resource/Script/Cainiao/Cainiao_remove_ads.js,tag=首页底部商品推广

[MITM]
hostname = cn-acs.m.cainiao.com
